events { worker_connections 1024; }

http {
    upstream backend_servers {
        server 172.31.63.124:8080 max_fails=0; # 스프링앱 1
        server 172.31.55.56:8080 max_fails=0; # 스프링앱 2 (새로 만들 곳)
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}